# This code is licensed from CircleCI to the user under the MIT license.
# See here for details: https://circleci.com/developer/orbs/licensing
version: 2.1
description: >
  Executing Katalon tests with your CircleCI CI/CD pipeline easily with the Katalon orb
display:
  home_url: https://docs.katalon.com/katalon-studio/docs/integration-circleci.html
  source_url: https://github.com/katalon-studio/katalon-circleci-orb
orbs:
examples:
  execute_sample_test:
    description: Executing a test suite with the latest version of Katalon Studio
    usage:
      version: 2.1
      orbs:
        katalon-studio: katalon/katalon-studio@23.0.12 #replace 23.0.12 with the latest version of Katalon Orb
      workflows:
       build:
        jobs:
            - katalon-studio/run:
                    version: "latest"
                    command_arguments: "-browserType='Chrome' -retry=0 -statusDelay=15 -testSuitePath='Test Suites/TS_RegressionTest' -apikey='1a76271f-d2c0-4079-b892-98e59860ebcf'"
